name: Pipeline de Deploy Julio Studio (Nativo Ultra-Fast)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: 📥 Checkout do Código-Fonte
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: 🛠️ Configurar Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: 🟢 Configurar Node.js (Runtime Técnico do CSS)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 🎨 Instalar Compilador de CSS e Módulos do Tailwind (V3 Lock)
        # Forçamos o tailwindcss@3 para dar match perfeito com o seu main.css e postcss.config.js
        run: npm install -g postcss postcss-cli autoprefixer tailwindcss@3

      - name: 🏗️ Compilar Site Estático
        run: hugo --gc --minify --cleanDestinationDir --baseURL "https://juliostudio.dev.br/"

      - name: 📦 Upload do Artefato (GitHub Pages Nativo)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: 🚀 Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4